<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="Cinthia roa and Winston Bravo">
    <link rel="icon" type="image/png" href="Imagenes/book(48).ico" />
      <link rel="stylesheet" type="text/css" href="css/style.css">
    <title>HappyBooks</title>

    <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
    
    
<script type="text/javascript" src='http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'></script>



    </head>
    
<body style="margin-top:5%">




  